version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent-bus-app
    restart: unless-stopped
    volumes:
      - ./.env:/var/www/.env
      - agent-bus-storage:/var/www/storage
      - agent-bus-logs:/var/www/storage/logs
    environment:
      - APP_NAME=Agent Bus
      - APP_ENV=production
      - APP_KEY=base64:r6aFDiiaKqYqbb9jfEKZRS+n4AFtbBw1tfdlDWj771o=
      - APP_DEBUG=false
      - APP_URL=https://agent-muliajaya.ffatahilah.my.id
      - DB_CONNECTION=mysql
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_DATABASE=agent_booking
      - DB_USERNAME=ffatahilah
      - DB_PASSWORD=OmbaInam#121221
      - SESSION_DRIVER=file
      - CACHE_STORE=file
      - QUEUE_CONNECTION=database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agent-bus.rule=Host(`agent-muliajaya.ffatahilah.my.id`)"
      - "traefik.http.routers.agent-bus.entrypoints=websecure"
      - "traefik.http.routers.agent-bus.tls=true"
      - "traefik.http.routers.agent-bus.tls.certresolver=letsencrypt"
      - "traefik.http.services.agent-bus.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_net"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  agent-bus-storage:
    driver: local
  agent-bus-logs:
    driver: local
